"""add user and task tables

Revision ID: ace4f183072f
Revises: 
Create Date: 2026-07-23 15:07:39.754414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ace4f183072f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), sa.Identity(always=True, start=1, increment=1), nullable=False),
    sa.Column('username', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('hashed_password', sa.Text(), nullable=False),
    sa.Column('admin', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("email ~* '^[A-Za-z0-9._%%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$'", name='ck_email_valid_email'),
    sa.CheckConstraint("username ~ '^[A-Za-z0-9._]+$'", name='ck_user_valid_username'),
    sa.CheckConstraint('length(username) >= 8', name='ck_users_username_minlength'),
    sa.PrimaryKeyConstraint('id', name='pk_user'),
    sa.UniqueConstraint('username', 'email', name='uq_user_email_username')
    )
    op.create_table('task',
    sa.Column('id', sa.Integer(), sa.Identity(always=True, start=1, increment=1), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('stat', sa.Enum('ongoing', 'complete', 'cancelled', name='status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("name ~* '^[A-Za-z0-9._]+$'", name='ck_task_user_valid_taskname'),
    sa.CheckConstraint('length(description) >= 8'),
    sa.CheckConstraint('length(name) BETWEEN 8 AND 32', name='ck_task_user_username_minlength'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_task_user', onupdate='RESTRICT', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_task'),
    sa.UniqueConstraint('name', name='uq_task_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    op.drop_table('user')

    # Drop the enum type in Postgres
    op.execute("DROP TYPE status;")
    # ### end Alembic commands ###
