"""Add users table

Revision ID: e69b946e9eec
Revises: 
Create Date: 2026-07-22 13:35:36.987668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e69b946e9eec'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), sa.Identity(always=True, start=1, increment=1), nullable=False),
    sa.Column('username', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('hashed_password', sa.Text(), nullable=False),
    sa.Column('admin', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("email ~ \'^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$\'", name='ck_email_valid_email'),
    sa.CheckConstraint('length(username) >= 8', name='ck_users_username_minlength'),
    sa.CheckConstraint('username ~ \'^[A-Za-z0-9._]+$\'', name='ck_user_valid_username'),
    sa.PrimaryKeyConstraint('id', name='pk_user'),
    sa.UniqueConstraint('username', 'email', name='uq_user_email_username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
